---
provisioner:
  name: chef_zero
  channel: stable
  product_name: chef
  product_version: 17.8.25
  chef_license: accept
  deprecations_as_errors: false

driver:
  name: vagrant

platforms:
  - name: ubuntu-20.04

suites:
  - name: default
    run_list:
      - recipe[letsencryptaws_test::gen_keystores]
      - recipe[letsencryptaws::default]
      - recipe[letsencryptaws::certbot]
    attributes:
      aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
      aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
      letsencryptaws:
        test_certs: true
        sync_path: letsencrypt-test
        data_bag: letsencryptaws
        data_bag_item: credentials
