# This is a basic workflow to help you get started with Actions

name: PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.38.0
      with:
        # Engine and version to use, see the syntax in the README. Reads from .ruby-version or .tool-versions if unset.
        ruby-version: 2.7
        # The version of Bundler to install. Either none, 1, 2, latest or Gemfile.lock. The default tries Gemfile.lock and otherwise uses latest.
        bundler: 2
        bundler-cache: true

    # Runs a set of commands using the runners shell
    - name: Install Gems
      run: bundle install
    - name: Cookstyle
      run: bundle exec cookstyle --version && bundle exec cookstyle --color --fail-level C .
    - name: RSpec
      run: bundle exec rspec --force-color --format doc
